'''
DMG Gameboy Emulator Project - MorganPG

gen_boilerplate.py:

Basic CPU Instruction Decoder Boilerplate Generator
This generates a huge match-case based instruction decoder (does not perform the execution of the instructions however)
'''
import json
import datetime
data:dict = {}

temp_datestring = datetime.datetime.now().strftime("%d/%m/%y %H:%M:%S")
outs = "#DMG Gameboy Emulator Project - MorganPG (dmg-emu-py)\n"
outs += f"#Autogenerated boilerplate from gen_boilerplate.py at {temp_datestring}\n\n"
outs += "#Notes: \n"
outs += "#Handlers follow the format handle_...(opcode, ..., flags:str, cycles:list[int]): \n"
outs += "#handle_inc_*b has an extra argument which is True for decrement and False for increment \n"
outs += "#handle_jr_imm8, handle_jp_imm16, handle_ret and handle_call_imm16 have an extra argument which is True for conditionals \n"
outs += "#handle_alu_8b has an extra argument which is True if the instruction uses immediate values \n"
outs += "#handle_stack has an extra argument which is True if the instruction is POP * and False if it is PUSH * \n"
outs += "#handle_int_control has an extra argument which is True if the interrupts should be enabled and False if they should be disabled \n"

outs += "\n#COPY THIS FUNCTION INTO CPU CLASS\n"
outs += "def handle_instruction(self, opcode):\n"
outs += "   match opcode:\n"

with open("opcodes.json") as f:
    data = json.load(f)["unprefixed"]

for val, inst in data.items():
    val_int = int(val, 16)

    inst_str = inst["mnemonic"]
    operands = inst["operands"]
    cycles = inst["cycles"]

    flag_str = ""

    for _, setting in inst["flags"].items():
        flag_str += setting

    is_illegal = "ILLEGAL" in inst_str


    for i, operand in enumerate(operands):
        immediate = operand["immediate"]
        increment = operand["increment"] if "increment" in operand else False
        decrement = operand["decrement"] if "decrement" in operand else False
                
        name = operand["name"]
        name += "+" if increment else ""
        name += "-" if decrement else ""

        op_str = ", " if i > 0 else " "
        op_str = f"{op_str}{name}" if immediate else f"{op_str}[{name}]"

        inst_str += op_str

    
    outs += f"     case {val}: #{inst_str}\n"
    if is_illegal:
        outs += f"        raise NotImplementedError('Undefined opcode {val}')\n" 
    elif (val_int & 0b11001111) == 1:
        outs += f"        self.handle_ld_r16_imm16(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11001111) == 2:
        outs += f"        self.handle_ld_r16mem_a(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11001111) == 10:
        outs += f"        self.handle_ld_a_r16mem(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif val_int == 8:
        outs += f"        self.handle_ld_imm16_sp(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11001111) == 3:
        outs += f"        self.handle_inc_16b(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11001111) == 11:
        outs += f"        self.handle_inc_16b(opcode, True, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11001111) == 9:
        outs += f"        self.handle_add_hl_r16(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11000111) == 4:
        outs += f"        self.handle_inc_8b(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11000111) == 5:
        outs += f"        self.handle_inc_8b(opcode, True, flags='{flag_str}', cycles={cycles})\n"    
    elif (val_int & 0b11000111) == 6:
        outs += f"        self.handle_ld_r8_imm8(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11000111) == 7:
        outs += f"        self.handle_flags_etc(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 24:
        outs += f"        self.handle_jr_imm8(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11100111) == 32:
        outs += f"        self.handle_jr_imm8(opcode, True, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 16:
        outs += f"        self.handle_stop(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11000000) == 64:
        outs += f"        self.handle_ld_r8_r8(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11000000) == 128:
        outs += f"        self.handle_alu_8b(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11000111) == 198:
        outs += f"        self.handle_alu_8b(opcode, True, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11100111) == 192:
        outs += f"        self.handle_ret(opcode, True, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 201:
        outs += f"        self.handle_ret(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 217:
        outs += f"        self.handle_reti(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11100111) == 194:
        outs += f"        self.handle_jp_imm16(opcode, True, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 195:
        outs += f"        self.handle_jp_imm16(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 233:
        outs += f"        self.handle_jp_hl(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11100111) == 196:
        outs += f"        self.handle_call_imm16(opcode, True, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 205:
        outs += f"        self.handle_call_imm16(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11000111) == 199:
        outs += f"        self.handle_rst(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11001111) == 193:
        outs += f"        self.handle_stack(opcode, True, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11001111) == 197:
        outs += f"        self.handle_stack(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 203:
        outs += f"        self.handle_prefix(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 226:
        outs += f"        self.handle_ldh_c_a(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 224:
        outs += f"        self.handle_ldh_imm8_a(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 234:
        outs += f"        self.handle_ld_imm16_a(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 242:
        outs += f"        self.handle_ldh_a_c(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 240:
        outs += f"        self.handle_ldh_a_imm8(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 250:
        outs += f"        self.handle_ld_a_imm16(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 232:
        outs += f"        self.handle_add_sp_imm8(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 248:
        outs += f"        self.handle_ld_hl_sp_imm8(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 249:
        outs += f"        self.handle_ld_sp_hl(opcode, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 243:
        outs += f"        self.handle_int_control(opcode, False, flags='{flag_str}', cycles={cycles})\n"
    elif (val_int & 0b11111111) == 251:
        outs += f"        self.handle_int_control(opcode, True, flags='{flag_str}', cycles={cycles})\n"
    else:
        outs += "        pass\n"

print(outs)