import json
import datetime
data:dict = {}

temp_datestring = datetime.datetime.now().strftime("%d/%m/%y %H:%M:%S")
outs = f"#Autogenerated boilerplate from gen_boilerplate.py at {temp_datestring}\n"
outs += "#STUBS (DO NOT COPY THESE)\n"
outs += "def handle_prefix(opcode):\n     pass\n"
outs += "def handle_load(opcode, is_ldh):\n     pass\n"
outs += "def handle_arithmetic(opcode):\n     pass\n"
outs += "def handle_logic(opcode):\n     pass\n"
outs += "def handle_jump(opcode, is_call):\n     pass\n"
outs += "def handle_return(opcode):\n     pass\n"
outs += "def handle_rotate_shift(opcode):\n     pass\n"
outs += "def handle_stack(opcode, is_pop):\n     pass\n"
outs += "def handle_increment(opcode, is_decrement):\n     pass\n"

outs += "\n#COPY THIS FUNCTION INTO CPU CLASS\n"
outs += "def handle_instruction(self, opcode):\n"
outs += "   match opcode:\n"

with open("opcodes.json") as f:
    data = json.load(f)["unprefixed"]

for val, inst in data.items():
    inst_str = inst["mnemonic"]
    operands = inst["operands"]
    is_illegal = "ILLEGAL" in inst_str
    is_ld = inst_str == "LD"
    is_ldh = inst_str == "LDH"
    is_arithmetic = inst_str in ["ADD","ADC","SUB","SBC"]
    is_logic = inst_str in ["AND","OR","XOR","CP"]
    is_jp = inst_str in ["JP", "JR"]
    is_call = inst_str in ["CALL", "RST"]
    is_ret = inst_str in ["RET", "RETI"]
    is_rsh = inst_str in ["RLCA", "RRCA", "RLA", "RRA"]
    is_push = inst_str == "PUSH"
    is_pop = inst_str == "POP"
    is_prefix = inst_str == "PREFIX"
    is_inc = inst_str == "INC"
    is_dec = inst_str == "DEC"

    for i, operand in enumerate(operands):
        immediate = operand["immediate"]
        increment = operand["increment"] if "increment" in operand else False
        decrement = operand["decrement"] if "decrement" in operand else False
                
        name = operand["name"]
        name += "+" if increment else ""
        name += "-" if decrement else ""

        op_str = ", " if i > 0 else " "
        op_str = f"{op_str}{name}" if immediate else f"{op_str}[{name}]"

        inst_str += op_str

    
    outs += f"     case {val}: #{inst_str}\n"
    if is_illegal:
        outs += f"        raise NotImplementedError('Undefined opcode {val}')\n" 
    elif is_prefix:
        outs += f"        self.handle_prefix(opcode)\n"
    elif is_ld:
        outs += f"        self.handle_load(opcode, False)\n"
    elif is_ldh:
        outs += f"        self.handle_load(opcode, True)\n"
    elif is_arithmetic:
        outs += f"        self.handle_arithmetic(opcode)\n"
    elif is_logic:
        outs += f"        self.handle_logic(opcode)\n"
    elif is_jp:
        outs += f"        self.handle_jump(opcode, False)\n"
    elif is_call:
        outs += f"        self.handle_jump(opcode, True)\n"
    elif is_ret:
        outs += f"        self.handle_return(opcode)\n"
    elif is_rsh:
        outs += f"        self.handle_rotate_shift(opcode)\n"
    elif is_push:
        outs += f"        self.handle_stack(opcode, False)\n"
    elif is_pop:
        outs += f"        self.handle_stack(opcode, True)\n"
    elif is_inc:
        outs += f"        self.handle_increment(opcode, False)\n"
    elif is_dec:
        outs += f"        self.handle_increment(opcode, True)\n"

    else:
        outs += "        pass\n"

print(outs)